// Code generated by MockGen. DO NOT EDIT.
// Source: ./query/sql_builder.go
//
// Generated by this command:
//
//	mockgen -source ./query/sql_builder.go -destination ./tests/mock/query/sql_builder.go
//

// Package mock_query is a generated GoMock package.
package mock_query
