name: "Test"

on: 
  push: 
    branches: 
      - main
  pull_request: 
    branches: 
      - main

jobs: 
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set Up Go Environment
        uses: actions/setup-go@v2
        with: 
          go-version: 1.21.1

      - name: Run Test
        run: make run-tests